/**
 * Regenerate `src/RegistrySnapshot.ts` — the vendored snapshot of the ACP
 * agent registry (https://agentclientprotocol.com, published at
 * https://cdn.agentclientprotocol.com/registry/v1/latest/registry.json).
 *
 * Usage:
 *   pnpm tsx scripts/generate-registry-snapshot.ts               # fetch the published index
 *   pnpm tsx scripts/generate-registry-snapshot.ts <registry-dir> # read a local checkout of agent.json dirs
 *
 * Only launch-relevant fields are kept (id, name, version, distribution), so
 * the snapshot stays a bounded catalog, not a mirror.
 */

import * as fs from "node:fs"
import * as path from "node:path"
import * as url from "node:url"

const registryUrl = "https://cdn.agentclientprotocol.com/registry/v1/latest/registry.json"

interface RawAgent {
  readonly id?: unknown
  readonly name?: unknown
  readonly version?: unknown
  readonly distribution?: unknown
}

const record = (value: unknown): Record<string, unknown> =>
  typeof value === "object" && value !== null && !Array.isArray(value) ? value as Record<string, unknown> : {}

const text = (value: unknown): string => (typeof value === "string" ? value : "")

const stringArray = (value: unknown): Array<string> =>
  Array.isArray(value) ? value.filter((entry): entry is string => typeof entry === "string") : []

const normalizeDistribution = (value: unknown): Record<string, unknown> => {
  const distribution = record(value)
  const out: Record<string, unknown> = {}
  const npx = record(distribution["npx"])
  if (text(npx["package"]) !== "") {
    out["npx"] = { package: text(npx["package"]), args: stringArray(npx["args"]) }
  }
  const uvx = record(distribution["uvx"])
  if (text(uvx["package"]) !== "") {
    out["uvx"] = { package: text(uvx["package"]), args: stringArray(uvx["args"]) }
  }
  const binary = record(distribution["binary"])
  const platforms: Record<string, unknown> = {}
  for (const [platform, raw] of Object.entries(binary)) {
    const target = record(raw)
    if (text(target["archive"]) === "" || text(target["cmd"]) === "") {
      continue
    }
    platforms[platform] = {
      archive: text(target["archive"]),
      sha256: text(target["sha256"]),
      cmd: text(target["cmd"]),
      args: stringArray(target["args"])
    }
  }
  if (Object.keys(platforms).length > 0) {
    out["binary"] = platforms
  }
  return out
}

const normalizeAgent = (raw: RawAgent): Record<string, unknown> | undefined => {
  const id = text(raw.id)
  if (id === "") {
    return undefined
  }
  const distribution = normalizeDistribution(raw.distribution)
  if (Object.keys(distribution).length === 0) {
    return undefined
  }
  return { id, name: text(raw.name), version: text(raw.version), distribution }
}

const loadAgents = async (): Promise<Array<Record<string, unknown>>> => {
  const sourceDir = process.argv[2]
  if (sourceDir !== undefined) {
    const agents: Array<Record<string, unknown>> = []
    for (const entry of fs.readdirSync(sourceDir).sort()) {
      const file = path.join(sourceDir, entry, "agent.json")
      if (!fs.existsSync(file)) {
        continue
      }
      const parsed: unknown = JSON.parse(fs.readFileSync(file, "utf8"))
      const agent = normalizeAgent(record(parsed) as RawAgent)
      if (agent !== undefined) {
        agents.push(agent)
      }
    }
    return agents
  }
  const response = await fetch(registryUrl)
  if (!response.ok) {
    throw new Error(`registry fetch failed: ${response.status}`)
  }
  const body = record(await response.json())
  const raw = Array.isArray(body["agents"]) ? body["agents"] : []
  const agents: Array<Record<string, unknown>> = []
  for (const entry of raw) {
    const agent = normalizeAgent(record(entry) as RawAgent)
    if (agent !== undefined) {
      agents.push(agent)
    }
  }
  agents.sort((a, b) => text(a["id"]).localeCompare(text(b["id"])))
  return agents
}

const main = async (): Promise<void> => {
  const agents = await loadAgents()
  const here = path.dirname(url.fileURLToPath(import.meta.url))
  const target = path.join(here, "..", "src", "RegistrySnapshot.ts")
  const header = [
    "/**",
    " * Vendored snapshot of the ACP agent registry",
    " * (https://cdn.agentclientprotocol.com/registry/v1/latest/registry.json).",
    " *",
    " * GENERATED by scripts/generate-registry-snapshot.ts — do not edit by hand.",
    ` * Snapshot date: ${new Date().toISOString().slice(0, 10)}. ${agents.length} agents.`,
    " *",
    " * The controller consults this snapshot (never the network) to resolve a",
    " * requested agent id into launch metadata when the operator has opted in",
    " * with `--allow registry-agents`.",
    " */",
    "",
    "export interface RegistryBinaryTarget {",
    "  readonly archive: string",
    "  readonly sha256: string",
    "  readonly cmd: string",
    "  readonly args: ReadonlyArray<string>",
    "}",
    "",
    "export interface RegistryPackageDistribution {",
    "  readonly package: string",
    "  readonly args: ReadonlyArray<string>",
    "}",
    "",
    "export interface RegistryDistribution {",
    "  readonly npx?: RegistryPackageDistribution",
    "  readonly uvx?: RegistryPackageDistribution",
    "  readonly binary?: Readonly<Record<string, RegistryBinaryTarget>>",
    "}",
    "",
    "export interface RegistryAgent {",
    "  readonly id: string",
    "  readonly name: string",
    "  readonly version: string",
    "  readonly distribution: RegistryDistribution",
    "}",
    "",
    "export const registrySnapshot: ReadonlyArray<RegistryAgent> = "
  ].join("\n")
  const body = JSON.stringify(agents, null, 2)
  fs.writeFileSync(target, `${header}${body}\n`)
  console.log(`wrote ${target} (${agents.length} agents)`)
}

main().catch((cause: unknown) => {
  console.error(cause)
  process.exit(1)
})
