/**
 * Vendored snapshot of the ACP agent registry
 * (https://cdn.agentclientprotocol.com/registry/v1/latest/registry.json).
 *
 * GENERATED by scripts/generate-registry-snapshot.ts — do not edit by hand.
 * Snapshot date: 2026-08-18. 39 agents.
 *
 * The controller consults this snapshot (never the network) to resolve a
 * requested agent id into launch metadata when the operator has opted in
 * with `--allow registry-agents`.
 */

export interface RegistryBinaryTarget {
  readonly archive: string
  readonly sha256: string
  readonly cmd: string
  readonly args: ReadonlyArray<string>
}

export interface RegistryPackageDistribution {
  readonly package: string
  readonly args: ReadonlyArray<string>
}

export interface RegistryDistribution {
  readonly npx?: RegistryPackageDistribution
  readonly uvx?: RegistryPackageDistribution
  readonly binary?: Readonly<Record<string, RegistryBinaryTarget>>
}

export interface RegistryAgent {
  readonly id: string
  readonly name: string
  readonly version: string
  readonly distribution: RegistryDistribution
}

export const registrySnapshot: ReadonlyArray<RegistryAgent> = [
  {
    "id": "agoragentic-acp",
    "name": "Agoragentic",
    "version": "1.3.0",
    "distribution": {
      "npx": {
        "package": "agoragentic-mcp@1.3.0",
        "args": [
          "--acp"
        ]
      }
    }
  },
  {
    "id": "amp-acp",
    "name": "Amp",
    "version": "0.9.0",
    "distribution": {
      "binary": {
        "darwin-aarch64": {
          "archive": "https://github.com/tao12345666333/amp-acp/releases/download/v0.9.0/amp-acp-darwin-aarch64.tar.gz",
          "sha256": "240a1a464f2a400ae51e9613b7f52b2abb6e7a29759001e9185291325671ccf1",
          "cmd": "./amp-acp",
          "args": []
        },
        "darwin-x86_64": {
          "archive": "https://github.com/tao12345666333/amp-acp/releases/download/v0.9.0/amp-acp-darwin-x86_64.tar.gz",
          "sha256": "0dc6d1ab8054e09b10ef49eea3e61afe363473d785bc9682ecb997480ec2f61f",
          "cmd": "./amp-acp",
          "args": []
        },
        "linux-aarch64": {
          "archive": "https://github.com/tao12345666333/amp-acp/releases/download/v0.9.0/amp-acp-linux-aarch64.tar.gz",
          "sha256": "b9e365221838b1a6e177c2fcd8f25a30086c3630e0330f1f6f74b25d2d4126c2",
          "cmd": "./amp-acp",
          "args": []
        },
        "linux-x86_64": {
          "archive": "https://github.com/tao12345666333/amp-acp/releases/download/v0.9.0/amp-acp-linux-x86_64.tar.gz",
          "sha256": "afaa50a152eb86a8ff21e354ded63fe2d21b730859692e3a60b2c4c9ef23df31",
          "cmd": "./amp-acp",
          "args": []
        },
        "windows-x86_64": {
          "archive": "https://github.com/tao12345666333/amp-acp/releases/download/v0.9.0/amp-acp-windows-x86_64.zip",
          "sha256": "3b2c3d14d703fcf9572da9733e4941703a7744bd37ec4aaa75421d6002c0157b",
          "cmd": "amp-acp.exe",
          "args": []
        }
      }
    }
  },
  {
    "id": "auggie",
    "name": "Auggie CLI",
    "version": "0.35.0",
    "distribution": {
      "npx": {
        "package": "@augmentcode/auggie@0.35.0",
        "args": [
          "--acp"
        ]
      }
    }
  },
  {
    "id": "autohand",
    "name": "Autohand Code",
    "version": "0.2.1",
    "distribution": {
      "npx": {
        "package": "@autohandai/autohand-acp@0.2.1",
        "args": []
      }
    }
  },
  {
    "id": "claude-acp",
    "name": "Claude Agent",
    "version": "0.69.0",
    "distribution": {
      "npx": {
        "package": "@agentclientprotocol/claude-agent-acp@0.69.0",
        "args": []
      }
    }
  },
  {
    "id": "cline",
    "name": "Cline",
    "version": "3.0.55",
    "distribution": {
      "npx": {
        "package": "cline@3.0.55",
        "args": [
          "--acp"
        ]
      }
    }
  },
  {
    "id": "codebuddy-code",
    "name": "Codebuddy Code",
    "version": "2.106.7",
    "distribution": {
      "npx": {
        "package": "@tencent-ai/codebuddy-code@2.106.7",
        "args": [
          "--acp"
        ]
      }
    }
  },
  {
    "id": "codex-acp",
    "name": "Codex",
    "version": "1.4.0",
    "distribution": {
      "npx": {
        "package": "@agentclientprotocol/codex-acp@1.4.0",
        "args": []
      }
    }
  },
  {
    "id": "cortex-code",
    "name": "Cortex Code",
    "version": "1.0.73",
    "distribution": {
      "binary": {
        "darwin-aarch64": {
          "archive":
            "https://sfc-repo.snowflakecomputing.com/cortex-code-cli/a4643c4278/1.0.73%2B180523.e6179a031de9/coco-1.0.73%2B180523.e6179a031de9-darwin-arm64.tar.gz",
          "sha256": "",
          "cmd": "./coco-1.0.73+180523.e6179a031de9-darwin-arm64/cortex",
          "args": [
            "acp",
            "serve"
          ]
        },
        "darwin-x86_64": {
          "archive":
            "https://sfc-repo.snowflakecomputing.com/cortex-code-cli/a4643c4278/1.0.73%2B180523.e6179a031de9/coco-1.0.73%2B180523.e6179a031de9-darwin-amd64.tar.gz",
          "sha256": "",
          "cmd": "./coco-1.0.73+180523.e6179a031de9-darwin-amd64/cortex",
          "args": [
            "acp",
            "serve"
          ]
        },
        "linux-x86_64": {
          "archive":
            "https://sfc-repo.snowflakecomputing.com/cortex-code-cli/a4643c4278/1.0.73%2B180523.e6179a031de9/coco-1.0.73%2B180523.e6179a031de9-linux-amd64.tar.gz",
          "sha256": "",
          "cmd": "./coco-1.0.73+180523.e6179a031de9-linux-amd64/cortex",
          "args": [
            "acp",
            "serve"
          ]
        },
        "linux-aarch64": {
          "archive":
            "https://sfc-repo.snowflakecomputing.com/cortex-code-cli/a4643c4278/1.0.73%2B180523.e6179a031de9/coco-1.0.73%2B180523.e6179a031de9-linux-arm64.tar.gz",
          "sha256": "",
          "cmd": "./coco-1.0.73+180523.e6179a031de9-linux-arm64/cortex",
          "args": [
            "acp",
            "serve"
          ]
        },
        "windows-x86_64": {
          "archive":
            "https://sfc-repo.snowflakecomputing.com/cortex-code-cli/a4643c4278/1.0.73%2B180523.e6179a031de9/coco-1.0.73%2B180523.e6179a031de9-windows-amd64.tar.gz",
          "sha256": "",
          "cmd": "./coco-1.0.73+180523.e6179a031de9-windows-amd64/cortex.exe",
          "args": [
            "acp",
            "serve"
          ]
        },
        "windows-aarch64": {
          "archive":
            "https://sfc-repo.snowflakecomputing.com/cortex-code-cli/a4643c4278/1.0.73%2B180523.e6179a031de9/coco-1.0.73%2B180523.e6179a031de9-windows-arm64.tar.gz",
          "sha256": "",
          "cmd": "./coco-1.0.73+180523.e6179a031de9-windows-arm64/cortex.exe",
          "args": [
            "acp",
            "serve"
          ]
        }
      }
    }
  },
  {
    "id": "corust-agent",
    "name": "Corust Agent",
    "version": "0.6.0",
    "distribution": {
      "binary": {
        "darwin-aarch64": {
          "archive":
            "https://github.com/Corust-ai/corust-agent-release/releases/download/v0.6.0/agent-darwin-arm64.tar.gz",
          "sha256": "",
          "cmd": "./corust-agent-acp",
          "args": []
        },
        "darwin-x86_64": {
          "archive":
            "https://github.com/Corust-ai/corust-agent-release/releases/download/v0.6.0/agent-darwin-x64.tar.gz",
          "sha256": "",
          "cmd": "./corust-agent-acp",
          "args": []
        },
        "linux-x86_64": {
          "archive":
            "https://github.com/Corust-ai/corust-agent-release/releases/download/v0.6.0/agent-linux-x64.tar.gz",
          "sha256": "",
          "cmd": "./corust-agent-acp",
          "args": []
        },
        "windows-x86_64": {
          "archive": "https://github.com/Corust-ai/corust-agent-release/releases/download/v0.6.0/agent-windows-x64.zip",
          "sha256": "",
          "cmd": "./corust-agent-acp.exe",
          "args": []
        }
      }
    }
  },
  {
    "id": "crow-cli",
    "name": "crow-cli",
    "version": "0.1.24",
    "distribution": {
      "binary": {
        "darwin-aarch64": {
          "archive": "https://github.com/crow-cli/crow-cli/releases/download/v0.1.24/crow-cli-darwin-aarch64.tar.gz",
          "sha256": "",
          "cmd": "./crow-cli",
          "args": [
            "acp"
          ]
        },
        "darwin-x86_64": {
          "archive": "https://github.com/crow-cli/crow-cli/releases/download/v0.1.24/crow-cli-darwin-x86_64.tar.gz",
          "sha256": "",
          "cmd": "./crow-cli",
          "args": [
            "acp"
          ]
        },
        "linux-aarch64": {
          "archive": "https://github.com/crow-cli/crow-cli/releases/download/v0.1.24/crow-cli-linux-aarch64.tar.gz",
          "sha256": "",
          "cmd": "./crow-cli",
          "args": [
            "acp"
          ]
        },
        "linux-x86_64": {
          "archive": "https://github.com/crow-cli/crow-cli/releases/download/v0.1.24/crow-cli-linux-x86_64.tar.gz",
          "sha256": "",
          "cmd": "./crow-cli",
          "args": [
            "acp"
          ]
        },
        "windows-x86_64": {
          "archive": "https://github.com/crow-cli/crow-cli/releases/download/v0.1.24/crow-cli-windows-x86_64.zip",
          "sha256": "",
          "cmd": "./crow-cli.exe",
          "args": [
            "acp"
          ]
        }
      }
    }
  },
  {
    "id": "cursor",
    "name": "Cursor",
    "version": "2026.08.11",
    "distribution": {
      "binary": {
        "darwin-aarch64": {
          "archive": "https://downloads.cursor.com/lab/2026.08.11-e8db854/darwin/arm64/agent-cli-package.tar.gz",
          "sha256": "",
          "cmd": "./dist-package/cursor-agent",
          "args": [
            "acp"
          ]
        },
        "darwin-x86_64": {
          "archive": "https://downloads.cursor.com/lab/2026.08.11-e8db854/darwin/x64/agent-cli-package.tar.gz",
          "sha256": "",
          "cmd": "./dist-package/cursor-agent",
          "args": [
            "acp"
          ]
        },
        "linux-aarch64": {
          "archive": "https://downloads.cursor.com/lab/2026.08.11-e8db854/linux/arm64/agent-cli-package.tar.gz",
          "sha256": "",
          "cmd": "./dist-package/cursor-agent",
          "args": [
            "acp"
          ]
        },
        "linux-x86_64": {
          "archive": "https://downloads.cursor.com/lab/2026.08.11-e8db854/linux/x64/agent-cli-package.tar.gz",
          "sha256": "",
          "cmd": "./dist-package/cursor-agent",
          "args": [
            "acp"
          ]
        },
        "windows-aarch64": {
          "archive": "https://downloads.cursor.com/lab/2026.08.11-e8db854/windows/arm64/agent-cli-package.zip",
          "sha256": "",
          "cmd": "./dist-package\\cursor-agent.cmd",
          "args": [
            "acp"
          ]
        },
        "windows-x86_64": {
          "archive": "https://downloads.cursor.com/lab/2026.08.11-e8db854/windows/x64/agent-cli-package.zip",
          "sha256": "",
          "cmd": "./dist-package\\cursor-agent.cmd",
          "args": [
            "acp"
          ]
        }
      }
    }
  },
  {
    "id": "deepagents",
    "name": "DeepAgents",
    "version": "0.1.7",
    "distribution": {
      "npx": {
        "package": "deepagents-acp@0.1.7",
        "args": []
      }
    }
  },
  {
    "id": "devin",
    "name": "Devin",
    "version": "3000.4.25",
    "distribution": {
      "binary": {
        "darwin-aarch64": {
          "archive": "https://static.devin.ai/cli/3000.4.25/devin-3000.4.25-aarch64-apple-darwin.tar.gz",
          "sha256": "",
          "cmd": "./bin/devin",
          "args": [
            "acp"
          ]
        },
        "darwin-x86_64": {
          "archive": "https://static.devin.ai/cli/3000.4.25/devin-3000.4.25-x86_64-apple-darwin.tar.gz",
          "sha256": "",
          "cmd": "./bin/devin",
          "args": [
            "acp"
          ]
        },
        "linux-aarch64": {
          "archive": "https://static.devin.ai/cli/3000.4.25/devin-3000.4.25-aarch64-unknown-linux.tar.gz",
          "sha256": "",
          "cmd": "./bin/devin",
          "args": [
            "acp"
          ]
        },
        "linux-x86_64": {
          "archive": "https://static.devin.ai/cli/3000.4.25/devin-3000.4.25-x86_64-unknown-linux.tar.gz",
          "sha256": "",
          "cmd": "./bin/devin",
          "args": [
            "acp"
          ]
        },
        "windows-aarch64": {
          "archive": "https://static.devin.ai/cli/3000.4.25/devin-3000.4.25-aarch64-pc-windows.zip",
          "sha256": "",
          "cmd": "./bin\\devin.exe",
          "args": [
            "acp"
          ]
        },
        "windows-x86_64": {
          "archive": "https://static.devin.ai/cli/3000.4.25/devin-3000.4.25-x86_64-pc-windows.zip",
          "sha256": "",
          "cmd": "./bin\\devin.exe",
          "args": [
            "acp"
          ]
        }
      }
    }
  },
  {
    "id": "dimcode",
    "name": "DimCode",
    "version": "0.3.15",
    "distribution": {
      "npx": {
        "package": "dimcode@0.3.15",
        "args": [
          "acp"
        ]
      }
    }
  },
  {
    "id": "dirac",
    "name": "Dirac",
    "version": "0.4.37",
    "distribution": {
      "npx": {
        "package": "dirac-cli@0.4.37",
        "args": [
          "--acp"
        ]
      }
    }
  },
  {
    "id": "factory-droid",
    "name": "Factory Droid",
    "version": "0.198.0",
    "distribution": {
      "npx": {
        "package": "droid@0.198.0",
        "args": [
          "exec",
          "--output-format",
          "acp-daemon"
        ]
      }
    }
  },
  {
    "id": "fast-agent",
    "name": "fast-agent",
    "version": "0.10.1",
    "distribution": {
      "uvx": {
        "package": "fast-agent-acp==0.10.1",
        "args": [
          "-x"
        ]
      }
    }
  },
  {
    "id": "gemini",
    "name": "Gemini CLI",
    "version": "0.55.1",
    "distribution": {
      "npx": {
        "package": "@google/gemini-cli@0.55.1",
        "args": [
          "--acp"
        ]
      }
    }
  },
  {
    "id": "github-copilot",
    "name": "GitHub Copilot",
    "version": "1.532.0",
    "distribution": {
      "npx": {
        "package": "@github/copilot-language-server@1.532.0",
        "args": [
          "--acp"
        ]
      }
    }
  },
  {
    "id": "github-copilot-cli",
    "name": "GitHub Copilot",
    "version": "1.0.80",
    "distribution": {
      "npx": {
        "package": "@github/copilot@1.0.80",
        "args": [
          "--acp"
        ]
      }
    }
  },
  {
    "id": "glm-acp-agent",
    "name": "GLM Agent",
    "version": "1.5.0",
    "distribution": {
      "npx": {
        "package": "glm-acp-agent@1.5.0",
        "args": []
      }
    }
  },
  {
    "id": "goose",
    "name": "goose",
    "version": "1.46.0",
    "distribution": {
      "binary": {
        "darwin-aarch64": {
          "archive": "https://github.com/block/goose/releases/download/v1.46.0/goose-aarch64-apple-darwin.tar.bz2",
          "sha256": "de263fb06839de31345dff08aeba999ba165b023cd3cec7ec3bef20f6f4f7e73",
          "cmd": "./goose",
          "args": [
            "acp"
          ]
        },
        "darwin-x86_64": {
          "archive": "https://github.com/block/goose/releases/download/v1.46.0/goose-x86_64-apple-darwin.tar.bz2",
          "sha256": "b5b66f5d4966aac74998c63420c98b3e289ae498f0c120463ac0b8dbc2a40083",
          "cmd": "./goose",
          "args": [
            "acp"
          ]
        },
        "linux-aarch64": {
          "archive": "https://github.com/block/goose/releases/download/v1.46.0/goose-aarch64-unknown-linux-gnu.tar.bz2",
          "sha256": "b56da65ab1004832ce5524ed40ec6fbe38ba84dae654d0a8eb86be9d90086cf6",
          "cmd": "./goose",
          "args": [
            "acp"
          ]
        },
        "linux-x86_64": {
          "archive": "https://github.com/block/goose/releases/download/v1.46.0/goose-x86_64-unknown-linux-gnu.tar.bz2",
          "sha256": "a1cf4856a765d07d6b95689a53c7bca21fcc6e6d65c0dfd064fc704052b85a7b",
          "cmd": "./goose",
          "args": [
            "acp"
          ]
        },
        "windows-x86_64": {
          "archive": "https://github.com/block/goose/releases/download/v1.46.0/goose-x86_64-pc-windows-msvc.zip",
          "sha256": "a903273d165c4b2ac3d30aa861f2e00753b07a5d24d24e37b65e36c86f937a76",
          "cmd": "./goose-package\\goose.exe",
          "args": [
            "acp"
          ]
        }
      }
    }
  },
  {
    "id": "grok-build",
    "name": "Grok Build",
    "version": "1.0.5",
    "distribution": {
      "npx": {
        "package": "@xai-official/grok@1.0.5",
        "args": [
          "agent",
          "stdio"
        ]
      }
    }
  },
  {
    "id": "harn",
    "name": "Harn",
    "version": "0.10.103",
    "distribution": {
      "binary": {
        "darwin-aarch64": {
          "archive": "https://github.com/burin-labs/harn/releases/download/v0.10.103/harn-aarch64-apple-darwin.tar.gz",
          "sha256": "366150192837328364be7299f0765ac8938923115277a68b34dcc7e906a6f228",
          "cmd": "./harn",
          "args": [
            "serve",
            "acp"
          ]
        },
        "darwin-x86_64": {
          "archive": "https://github.com/burin-labs/harn/releases/download/v0.10.103/harn-x86_64-apple-darwin.tar.gz",
          "sha256": "d64b9248ea1b80fc184c9a41ac2e2ecac341aa11299c6e634957e7fa0546f425",
          "cmd": "./harn",
          "args": [
            "serve",
            "acp"
          ]
        },
        "linux-aarch64": {
          "archive":
            "https://github.com/burin-labs/harn/releases/download/v0.10.103/harn-aarch64-unknown-linux-gnu.tar.gz",
          "sha256": "64ff3424142e24df7838f23bab8ccaacabf547685ad1edefae5ed56668b76577",
          "cmd": "./harn",
          "args": [
            "serve",
            "acp"
          ]
        },
        "linux-x86_64": {
          "archive":
            "https://github.com/burin-labs/harn/releases/download/v0.10.103/harn-x86_64-unknown-linux-gnu.tar.gz",
          "sha256": "9c1a4c74c47c9146b5ac6360fb2554fdcfa717d1c0be450dc42f26144b61bbdd",
          "cmd": "./harn",
          "args": [
            "serve",
            "acp"
          ]
        },
        "windows-x86_64": {
          "archive": "https://github.com/burin-labs/harn/releases/download/v0.10.103/harn-x86_64-pc-windows-msvc.zip",
          "sha256": "06122e148c8155b35c33d5839049337bfe556cb7731b21a6b2dfb76fc20592df",
          "cmd": "harn.exe",
          "args": [
            "serve",
            "acp"
          ]
        }
      }
    }
  },
  {
    "id": "junie",
    "name": "Junie",
    "version": "2783.5.0",
    "distribution": {
      "binary": {
        "darwin-aarch64": {
          "archive":
            "https://github.com/JetBrains/junie-acp-release/releases/download/2783.5/junie-release-2783.5-macos-aarch64.zip",
          "sha256": "",
          "cmd": "./Applications/junie.app/Contents/MacOS/junie",
          "args": [
            "--acp=true"
          ]
        },
        "darwin-x86_64": {
          "archive":
            "https://github.com/JetBrains/junie-acp-release/releases/download/2783.5/junie-release-2783.5-macos-amd64.zip",
          "sha256": "",
          "cmd": "./Applications/junie.app/Contents/MacOS/junie",
          "args": [
            "--acp=true"
          ]
        },
        "linux-aarch64": {
          "archive":
            "https://github.com/JetBrains/junie-acp-release/releases/download/2783.5/junie-release-2783.5-linux-aarch64.zip",
          "sha256": "",
          "cmd": "./junie-app/bin/junie",
          "args": [
            "--acp=true"
          ]
        },
        "linux-x86_64": {
          "archive":
            "https://github.com/JetBrains/junie-acp-release/releases/download/2783.5/junie-release-2783.5-linux-amd64.zip",
          "sha256": "",
          "cmd": "./junie-app/bin/junie",
          "args": [
            "--acp=true"
          ]
        },
        "windows-x86_64": {
          "archive":
            "https://github.com/JetBrains/junie-acp-release/releases/download/2783.5/junie-release-2783.5-windows-amd64.zip",
          "sha256": "",
          "cmd": "./junie/junie.exe",
          "args": [
            "--acp=true"
          ]
        },
        "windows-aarch64": {
          "archive":
            "https://github.com/JetBrains/junie-acp-release/releases/download/2783.5/junie-release-2783.5-windows-aarch64.zip",
          "sha256": "",
          "cmd": "./junie/junie.exe",
          "args": [
            "--acp=true"
          ]
        }
      }
    }
  },
  {
    "id": "kilo",
    "name": "Kilo",
    "version": "7.4.22",
    "distribution": {
      "npx": {
        "package": "@kilocode/cli@7.4.22",
        "args": [
          "acp"
        ]
      },
      "binary": {
        "darwin-aarch64": {
          "archive": "https://github.com/Kilo-Org/kilocode/releases/download/v7.4.22/kilo-darwin-arm64.zip",
          "sha256": "32c79158e731d8662597ff38b91dd217c9bfefff55df472b7be584987822572c",
          "cmd": "./kilo",
          "args": [
            "acp"
          ]
        },
        "darwin-x86_64": {
          "archive": "https://github.com/Kilo-Org/kilocode/releases/download/v7.4.22/kilo-darwin-x64.zip",
          "sha256": "06e9c266c45d00d23939ad3544971848f2133ea4c81fbe9ddbfa0560ca84e1af",
          "cmd": "./kilo",
          "args": [
            "acp"
          ]
        },
        "linux-aarch64": {
          "archive": "https://github.com/Kilo-Org/kilocode/releases/download/v7.4.22/kilo-linux-arm64.tar.gz",
          "sha256": "ddac95f45c77b259c429ed81dfc2a453df88dde7e2d1a524419b53cdb150cf90",
          "cmd": "./kilo",
          "args": [
            "acp"
          ]
        },
        "linux-x86_64": {
          "archive": "https://github.com/Kilo-Org/kilocode/releases/download/v7.4.22/kilo-linux-x64.tar.gz",
          "sha256": "60b775a71e60e21d10b55a6cacd79711b0fdfe8e8545decec9fcaadf8b1ebdb3",
          "cmd": "./kilo",
          "args": [
            "acp"
          ]
        },
        "windows-x86_64": {
          "archive": "https://github.com/Kilo-Org/kilocode/releases/download/v7.4.22/kilo-windows-x64.zip",
          "sha256": "d2b06537e2610294f207ccc0dd8413d275f0d3248be00be7d9a4f716b4dcff0a",
          "cmd": "./kilo.exe",
          "args": [
            "acp"
          ]
        }
      }
    }
  },
  {
    "id": "kimi",
    "name": "Kimi CLI",
    "version": "1.49.0",
    "distribution": {
      "binary": {
        "darwin-aarch64": {
          "archive":
            "https://github.com/MoonshotAI/kimi-cli/releases/download/1.49.0/kimi-1.49.0-aarch64-apple-darwin.tar.gz",
          "sha256": "15018b20b203aee09658fdc64840c4846fc17c108d8dba1a19a95581d3ce2921",
          "cmd": "./kimi",
          "args": [
            "acp"
          ]
        },
        "linux-aarch64": {
          "archive":
            "https://github.com/MoonshotAI/kimi-cli/releases/download/1.49.0/kimi-1.49.0-aarch64-unknown-linux-gnu.tar.gz",
          "sha256": "5ac54cabce16ede27b9d2069b9b88edee25528646e7bb5befa9980a1ca71febb",
          "cmd": "./kimi",
          "args": [
            "acp"
          ]
        },
        "linux-x86_64": {
          "archive":
            "https://github.com/MoonshotAI/kimi-cli/releases/download/1.49.0/kimi-1.49.0-x86_64-unknown-linux-gnu.tar.gz",
          "sha256": "6ce0b83f583c45a64cc9f51ffe7e1a8e03ee79acda69945fcf8c23341b9d892f",
          "cmd": "./kimi",
          "args": [
            "acp"
          ]
        },
        "windows-aarch64": {
          "archive":
            "https://github.com/MoonshotAI/kimi-cli/releases/download/1.49.0/kimi-1.49.0-aarch64-pc-windows-msvc.zip",
          "sha256": "3ac8f05c7bd18d902a324c6c03a71084cfbe785b9669bbd556c071ee1d8f2f26",
          "cmd": "./kimi.exe",
          "args": [
            "acp"
          ]
        },
        "windows-x86_64": {
          "archive":
            "https://github.com/MoonshotAI/kimi-cli/releases/download/1.49.0/kimi-1.49.0-x86_64-pc-windows-msvc.zip",
          "sha256": "2acbbc7ca8c8ac4b03dab1d970f53a292bd226168151b423499feab9fc203ddd",
          "cmd": "./kimi.exe",
          "args": [
            "acp"
          ]
        }
      }
    }
  },
  {
    "id": "minion-code",
    "name": "Minion Code",
    "version": "0.1.44",
    "distribution": {
      "uvx": {
        "package": "minion-code@0.1.44",
        "args": [
          "acp"
        ]
      }
    }
  },
  {
    "id": "mistral-vibe",
    "name": "Mistral Vibe",
    "version": "2.24.1",
    "distribution": {
      "binary": {
        "darwin-aarch64": {
          "archive":
            "https://github.com/mistralai/mistral-vibe/releases/download/v2.24.1/vibe-acp-darwin-aarch64-2.24.1.tar.gz",
          "sha256": "4faa3ed31454ee739fac2d5ff052c56056b175611a7b7ace0a4191f2bf83ba93",
          "cmd": "./vibe-acp",
          "args": []
        },
        "darwin-x86_64": {
          "archive":
            "https://github.com/mistralai/mistral-vibe/releases/download/v2.24.1/vibe-acp-darwin-x86_64-2.24.1.tar.gz",
          "sha256": "97d512a02e97fb828824cfb7b72734574f086d0442851c5fdfb432d7dabfa88a",
          "cmd": "./vibe-acp",
          "args": []
        },
        "linux-aarch64": {
          "archive":
            "https://github.com/mistralai/mistral-vibe/releases/download/v2.24.1/vibe-acp-linux-aarch64-2.24.1.tar.gz",
          "sha256": "e43913b43f0666df2a42060cd3bd410805b0ca1218843b0c242edf874a78c31a",
          "cmd": "./vibe-acp",
          "args": []
        },
        "linux-x86_64": {
          "archive":
            "https://github.com/mistralai/mistral-vibe/releases/download/v2.24.1/vibe-acp-linux-x86_64-2.24.1.tar.gz",
          "sha256": "8e87f581e7c292fbeab7377178e947ddc4e83753c409f1db0760631f11d7083c",
          "cmd": "./vibe-acp",
          "args": []
        },
        "windows-x86_64": {
          "archive":
            "https://github.com/mistralai/mistral-vibe/releases/download/v2.24.1/vibe-acp-windows-x86_64-2.24.1.zip",
          "sha256": "a66329ff18845f8e810359910e8da15bb2071648159c13a10838e5ae7a7d9b81",
          "cmd": "./vibe-acp.exe",
          "args": []
        }
      }
    }
  },
  {
    "id": "nova",
    "name": "Nova",
    "version": "1.1.35",
    "distribution": {
      "npx": {
        "package": "@compass-ai/nova@1.1.35",
        "args": [
          "acp"
        ]
      }
    }
  },
  {
    "id": "opencode",
    "name": "OpenCode",
    "version": "1.18.18",
    "distribution": {
      "binary": {
        "darwin-aarch64": {
          "archive": "https://github.com/anomalyco/opencode/releases/download/v1.18.18/opencode-darwin-arm64.zip",
          "sha256": "7d668bf26496fec8686d4e51ebb1ac2bd2e393f0c1620aa696c4c242a9e5806a",
          "cmd": "./opencode",
          "args": [
            "acp"
          ]
        },
        "darwin-x86_64": {
          "archive": "https://github.com/anomalyco/opencode/releases/download/v1.18.18/opencode-darwin-x64.zip",
          "sha256": "9581bd7683a7528456179fb11e3377d9ef568e10a935611a2c6722e349454d83",
          "cmd": "./opencode",
          "args": [
            "acp"
          ]
        },
        "linux-aarch64": {
          "archive": "https://github.com/anomalyco/opencode/releases/download/v1.18.18/opencode-linux-arm64.tar.gz",
          "sha256": "dcb1b5ec5687b43f87749560021f9203f3809e0ce5ae44ff9be8ae17083fe4ba",
          "cmd": "./opencode",
          "args": [
            "acp"
          ]
        },
        "linux-x86_64": {
          "archive": "https://github.com/anomalyco/opencode/releases/download/v1.18.18/opencode-linux-x64.tar.gz",
          "sha256": "0cddc222418b8553669905a8980c0cda7088f00da24d83d6ac76b01c9fdb2aaf",
          "cmd": "./opencode",
          "args": [
            "acp"
          ]
        },
        "windows-aarch64": {
          "archive": "https://github.com/anomalyco/opencode/releases/download/v1.18.18/opencode-windows-arm64.zip",
          "sha256": "0d34d837ea3b5e10349d8550318083040a8b4c061d3faaa4eabd339984aa49b0",
          "cmd": "./opencode",
          "args": [
            "acp"
          ]
        },
        "windows-x86_64": {
          "archive": "https://github.com/anomalyco/opencode/releases/download/v1.18.18/opencode-windows-x64.zip",
          "sha256": "c6d265376fdb93164013671b0cf402410184f73c34fc15d82d40a16a745b15f4",
          "cmd": "./opencode.exe",
          "args": [
            "acp"
          ]
        }
      }
    }
  },
  {
    "id": "pi-acp",
    "name": "pi ACP",
    "version": "0.0.33",
    "distribution": {
      "npx": {
        "package": "pi-acp@0.0.33",
        "args": []
      }
    }
  },
  {
    "id": "poolside",
    "name": "Poolside",
    "version": "1.0.16",
    "distribution": {
      "binary": {
        "darwin-aarch64": {
          "archive": "https://downloads.poolside.ai/pool/v1.0.16/pool-darwin-arm64.tar.gz",
          "sha256": "0932af3eb2b57a863acacb664ec8b2b1d3a76c2570a788b086001608cc585f74",
          "cmd": "./pool-darwin-arm64",
          "args": [
            "acp"
          ]
        },
        "darwin-x86_64": {
          "archive": "https://downloads.poolside.ai/pool/v1.0.16/pool-darwin-amd64.tar.gz",
          "sha256": "6d75fae2d7de6c35b6b467b5f682935e3ecde8ff611cb620c56b7bd607e0afde",
          "cmd": "./pool-darwin-amd64",
          "args": [
            "acp"
          ]
        },
        "linux-aarch64": {
          "archive": "https://downloads.poolside.ai/pool/v1.0.16/pool-linux-arm64.tar.gz",
          "sha256": "466343b66b03ee4e66476fcc69be1eb5bf8e9155a4ab73e0e72a232d1f8d2a12",
          "cmd": "./pool-linux-arm64",
          "args": [
            "acp"
          ]
        },
        "linux-x86_64": {
          "archive": "https://downloads.poolside.ai/pool/v1.0.16/pool-linux-amd64.tar.gz",
          "sha256": "e86aa8c9feef003540673ab494e91bfadc273218d531c43d662cafb69e464146",
          "cmd": "./pool-linux-amd64",
          "args": [
            "acp"
          ]
        },
        "windows-aarch64": {
          "archive": "https://downloads.poolside.ai/pool/v1.0.16/pool-windows-arm64.tar.gz",
          "sha256": "8dc7d014ced3e9d3ced240bbc7dabaf696bf59f118bd271d9f4e8561e415d75b",
          "cmd": "./pool-windows-arm64.exe",
          "args": [
            "acp"
          ]
        },
        "windows-x86_64": {
          "archive": "https://downloads.poolside.ai/pool/v1.0.16/pool-windows-amd64.tar.gz",
          "sha256": "3e324f1a4b5855ba5363232c06461ec9d6d2ae1a341c827221e79779f8f2bc6f",
          "cmd": "./pool-windows-amd64.exe",
          "args": [
            "acp"
          ]
        }
      }
    }
  },
  {
    "id": "qoder",
    "name": "Qoder CLI",
    "version": "0.2.14",
    "distribution": {
      "npx": {
        "package": "@qoder-ai/qodercli@0.2.14",
        "args": [
          "--acp"
        ]
      }
    }
  },
  {
    "id": "qwen-code",
    "name": "Qwen Code",
    "version": "0.21.13",
    "distribution": {
      "npx": {
        "package": "@qwen-code/qwen-code@0.21.13",
        "args": [
          "--acp",
          "--experimental-skills"
        ]
      }
    }
  },
  {
    "id": "sigit",
    "name": "siGit Code",
    "version": "1.5.2",
    "distribution": {
      "npx": {
        "package": "@smbcloud/sigit@1.5.2",
        "args": []
      },
      "binary": {
        "darwin-aarch64": {
          "archive": "https://github.com/getsigit/sigit/releases/download/v1.5.2/sigit-macos-arm64.tar.gz",
          "sha256": "be17cca0bb7341ac43d0ec3769a75aa5ca4a91c6e3c24512a524f3318eccad08",
          "cmd": "./sigit",
          "args": []
        },
        "darwin-x86_64": {
          "archive": "https://github.com/getsigit/sigit/releases/download/v1.5.2/sigit-macos-amd64.tar.gz",
          "sha256": "dc24791071831e1b6c5b84b09868bb3af62baae71db565d31176becab82744bc",
          "cmd": "./sigit",
          "args": []
        },
        "linux-aarch64": {
          "archive": "https://github.com/getsigit/sigit/releases/download/v1.5.2/sigit-linux-arm64",
          "sha256": "374bf986b88b4736f4b1f7b16948f157002f7737a29a70140ee7036cd4735206",
          "cmd": "./sigit-linux-arm64",
          "args": []
        },
        "linux-x86_64": {
          "archive": "https://github.com/getsigit/sigit/releases/download/v1.5.2/sigit-linux-amd64",
          "sha256": "70bedf5d9459a86c9beea393a81a7a981c0fa07474b5ad0876ee62f6369d0d15",
          "cmd": "./sigit-linux-amd64",
          "args": []
        },
        "windows-aarch64": {
          "archive": "https://github.com/getsigit/sigit/releases/download/v1.5.2/sigit-win-arm64.exe",
          "sha256": "8982d36e86976eacec564989f13844ac0005263f3a5651ea7394a2c013d4b610",
          "cmd": "./sigit-win-arm64.exe",
          "args": []
        },
        "windows-x86_64": {
          "archive": "https://github.com/getsigit/sigit/releases/download/v1.5.2/sigit-win-amd64.exe",
          "sha256": "6d1a1f11f7d1e32a5995f9ea413e626f2e47dcc56fb000e30bf60cebb68e4f24",
          "cmd": "./sigit-win-amd64.exe",
          "args": []
        }
      }
    }
  },
  {
    "id": "stakpak",
    "name": "Stakpak",
    "version": "0.3.88",
    "distribution": {
      "binary": {
        "darwin-aarch64": {
          "archive": "https://github.com/stakpak/agent/releases/download/v0.3.88/stakpak-darwin-aarch64.tar.gz",
          "sha256": "",
          "cmd": "./stakpak",
          "args": [
            "acp"
          ]
        },
        "darwin-x86_64": {
          "archive": "https://github.com/stakpak/agent/releases/download/v0.3.88/stakpak-darwin-x86_64.tar.gz",
          "sha256": "",
          "cmd": "./stakpak",
          "args": [
            "acp"
          ]
        },
        "linux-aarch64": {
          "archive": "https://github.com/stakpak/agent/releases/download/v0.3.88/stakpak-linux-aarch64.tar.gz",
          "sha256": "",
          "cmd": "./stakpak",
          "args": [
            "acp"
          ]
        },
        "linux-x86_64": {
          "archive": "https://github.com/stakpak/agent/releases/download/v0.3.88/stakpak-linux-x86_64.tar.gz",
          "sha256": "",
          "cmd": "./stakpak",
          "args": [
            "acp"
          ]
        },
        "windows-x86_64": {
          "archive": "https://github.com/stakpak/agent/releases/download/v0.3.88/stakpak-windows-x86_64.zip",
          "sha256": "",
          "cmd": "./stakpak.exe",
          "args": [
            "acp"
          ]
        }
      }
    }
  },
  {
    "id": "vtcode",
    "name": "VT Code",
    "version": "0.96.14",
    "distribution": {
      "binary": {
        "darwin-aarch64": {
          "archive":
            "https://github.com/vinhnx/VTCode/releases/download/0.96.14/vtcode-0.96.14-aarch64-apple-darwin.tar.gz",
          "sha256": "",
          "cmd": "./vtcode",
          "args": [
            "acp"
          ]
        },
        "darwin-x86_64": {
          "archive":
            "https://github.com/vinhnx/VTCode/releases/download/0.96.14/vtcode-0.96.14-x86_64-apple-darwin.tar.gz",
          "sha256": "",
          "cmd": "./vtcode",
          "args": [
            "acp"
          ]
        },
        "linux-x86_64": {
          "archive":
            "https://github.com/vinhnx/VTCode/releases/download/0.96.14/vtcode-0.96.14-x86_64-unknown-linux-gnu.tar.gz",
          "sha256": "",
          "cmd": "./vtcode",
          "args": [
            "acp"
          ]
        },
        "windows-x86_64": {
          "archive":
            "https://github.com/vinhnx/VTCode/releases/download/0.96.14/vtcode-0.96.14-x86_64-pc-windows-msvc.zip",
          "sha256": "",
          "cmd": "vtcode.exe",
          "args": [
            "acp"
          ]
        }
      }
    }
  }
]
